CREATE TABLE IF NOT EXISTS users
(
  id BIGINT CONSTRAINT user_pk PRIMARY KEY,
  name VARCHAR(512) NOT NULL,
  password VARCHAR(32) NOT NULL
);

COMMENT ON TABLE users IS 'Пользователь';

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1;

CREATE TABLE IF NOT EXISTS events
(
    id BIGINT PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    date DATE NOT NULL,
    user_id BIGINT NOT NULL CONSTRAINT events_users_fk REFERENCES users (id)
);

COMMENT ON TABLE events IS 'Событие';

CREATE SEQUENCE IF NOT EXISTS events_id_seq START WITH 1;
